on: [push]
jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - name: Setup Ninja for Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install ninja-build
      - name: Setup build libraries on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev
      - name: Create build files for Ninja
        run:  cmake -DBUILD_SHARED_LIBS=False -G Ninja -S . -B ./Build
      - name: Build project with Ninja
        run:  ninja -C ./Build
